# NUMPY 

In [1]:
import numpy as np# import numpy library

In [2]:
arr=np.arange(1000000)
lis=list(range(1000000))

In [3]:
%time for _ in range(10):arr1=arr*2

Wall time: 40.8 ms


In [4]:
%time for _ in range(10):lis2=[x*2 for x in lis]

Wall time: 1.79 s


In [5]:
arr1

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [6]:
lis2

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [7]:
data=np.random.randn(2,3)

In [8]:
data


array([[-0.21129938, -0.20610246, -1.66646783],
       [-1.87328693, -0.74886288, -0.678401  ]])

In [9]:
data*10

array([[ -2.11299382,  -2.06102455, -16.66467827],
       [-18.73286926,  -7.4886288 ,  -6.78400997]])

In [10]:
data+data

array([[-0.42259876, -0.41220491, -3.33293565],
       [-3.74657385, -1.49772576, -1.35680199]])

In [11]:
data1=np.random.randn(2,3)

In [12]:
data1

array([[-0.80380202, -0.0067614 , -0.78960079],
       [ 1.16446227, -1.77933984,  0.75606572]])

In [13]:
data+data1

array([[-1.0151014 , -0.21286386, -2.45606862],
       [-0.70882466, -2.52820272,  0.07766473]])

In [14]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [16]:
data2=[3,4,5,6,7,7,88,89,9,9]
arr2=np.array(data2)

In [17]:
arr2

array([ 3,  4,  5,  6,  7,  7, 88, 89,  9,  9])

In [18]:
data3=[[2,4,5,6,7],[4,5,6,7,5]]
arr3=np.array(data3)

In [19]:
arr3

array([[2, 4, 5, 6, 7],
       [4, 5, 6, 7, 5]])

In [20]:
arr3.ndim # check the dimension of numpy array

2

In [21]:
arr3.shape

(2, 5)

In [22]:
arr3.dtype# to check the array data type

dtype('int32')

In [23]:
np.zeros(10) # make the array of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(10,dtype="int") #difine type int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.zeros((3,5)) #making the array of 3 X 5 size

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(10)#making the array of ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.ones((2,6),dtype="int") # define  the size and datatype

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [28]:
np.empty(100) #define the empty 

array([9.08672460e-312, 0.00000000e+000, 1.48539705e-313, 6.95187041e-310,
       9.08672461e-312, 5.92878775e-323, 9.08661252e-312, 1.69759663e-313,
       9.07656708e-307, 0.00000000e+000, 1.50690022e-321, 0.00000000e+000,
       1.90979621e-313, 4.94065646e-324, 9.08672461e-312, 5.92878775e-323,
       9.08661252e-312, 2.12199579e-313,             nan, 0.00000000e+000,
       1.50690022e-321, 0.00000000e+000, 2.33419537e-313, 4.94065646e-324,
       9.08670546e-312, 5.92878775e-323, 9.08661252e-312, 2.54639495e-313,
       0.00000000e+000, 0.00000000e+000, 1.50690022e-321, 0.00000000e+000,
       2.75859453e-313, 4.94065646e-324, 9.08724562e-312, 5.92878775e-323,
       9.08661252e-312, 2.97079411e-313, 0.00000000e+000, 0.00000000e+000,
       1.50690022e-321, 0.00000000e+000, 3.18299369e-313, 4.94065646e-324,
       9.08724562e-312, 5.92878775e-323, 9.08661252e-312, 3.39519327e-313,
       6.95187041e-310, 0.00000000e+000, 1.50690022e-321, 0.00000000e+000,
       3.60739284e-313, 4

In [29]:
np.arange(15)  # array of sequence

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.reshape(np.arange(15),(3,5),order="F") # order is used to change the the direction of the 2 dimension array

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [31]:
np.identity(3,int) # making he identiy matrix or array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
a=np.eye(3,dtype="int")
a  # this is also use to make the identity array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
a=a.astype(np.float64) # give the datatype of array

In [34]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
arr=np.array([1,4,5,2,8,9])

In [36]:
s=arr.astype(float)

In [37]:
n=np.array(['1.3','5.6'],dtype=np.string_)

In [38]:
n.astype(s.dtype)

array([1.3, 5.6])

In [39]:
arr=np.array([[3,4,5,7],[4,6,8,9]])
arr  

array([[3, 4, 5, 7],
       [4, 6, 8, 9]])

In [40]:
arr*arr

array([[ 9, 16, 25, 49],
       [16, 36, 64, 81]])

In [41]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
1/arr

array([[0.33333333, 0.25      , 0.2       , 0.14285714],
       [0.25      , 0.16666667, 0.125     , 0.11111111]])

In [43]:
arr2=np.array([[2,7,2,9],[3,5,8,9]])


In [44]:
a=arr>arr2

In [45]:
a.dtype

dtype('bool')

In [46]:
a

array([[ True, False,  True, False],
       [ True,  True, False, False]])

In [47]:
arr=np.arange(10)

# SLICING AND INDEXING

In [48]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[5]

5

In [50]:
arr[5:7]

array([5, 6])

In [51]:
arr[5:8]=16

In [52]:
arr

array([ 0,  1,  2,  3,  4, 16, 16, 16,  8,  9])

In [53]:
a=arr[4:8]

In [54]:
a

array([ 4, 16, 16, 16])

In [55]:
a[2]=5

In [56]:
arr

array([ 0,  1,  2,  3,  4, 16,  5, 16,  8,  9])

In [57]:
b=arr[4:8].copy()

In [58]:
b

array([ 4, 16,  5, 16])

In [59]:
b[3]=4

In [60]:
arr

array([ 0,  1,  2,  3,  4, 16,  5, 16,  8,  9])

In [61]:
a[2]=16

In [62]:
arr

array([ 0,  1,  2,  3,  4, 16, 16, 16,  8,  9])

In [63]:
b

array([ 4, 16,  5,  4])

In [64]:
arr=np.array([[1,2,3,4],[4,6,8,9],[3,5,8,1],[1,6,48,9]])

In [65]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  6,  8,  9],
       [ 3,  5,  8,  1],
       [ 1,  6, 48,  9]])

In [66]:
arr[1]

array([4, 6, 8, 9])

In [67]:
arr[1:-1,1:-1]=0 

In [68]:
arr

array([[ 1,  2,  3,  4],
       [ 4,  0,  0,  9],
       [ 3,  0,  0,  1],
       [ 1,  6, 48,  9]])

In [69]:
 arr=np.reshape(np.arange(16),(2,2,4))

In [70]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [71]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [72]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

# UNIVERSAL FUNCTION


In [73]:
arr=np.arange(10)

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [76]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [77]:
x=np.random.randn(10)

In [78]:
x

array([-0.68360446,  0.28168025, -0.31404478, -1.0368309 ,  0.27823887,
       -0.5179654 ,  0.16541101,  1.15998801, -0.55494247,  0.22789281])

In [79]:
y=np.random.randn(10)

In [80]:
y

array([ 2.15468422, -0.45213109, -0.65136373, -0.81858399,  0.12808975,
       -0.65354293,  0.11203314,  0.12101516,  1.51914533,  1.36998895])

In [81]:
np.maximum(x,y)

array([ 2.15468422,  0.28168025, -0.31404478, -0.81858399,  0.27823887,
       -0.5179654 ,  0.16541101,  1.15998801,  1.51914533,  1.36998895])

In [82]:
np.minimum(x,y)

array([-0.68360446, -0.45213109, -0.65136373, -1.0368309 ,  0.12808975,
       -0.65354293,  0.11203314,  0.12101516, -0.55494247,  0.22789281])

In [83]:
np.abs(x)

array([0.68360446, 0.28168025, 0.31404478, 1.0368309 , 0.27823887,
       0.5179654 , 0.16541101, 1.15998801, 0.55494247, 0.22789281])

In [84]:
np.fabs(x)

array([0.68360446, 0.28168025, 0.31404478, 1.0368309 , 0.27823887,
       0.5179654 , 0.16541101, 1.15998801, 0.55494247, 0.22789281])

In [85]:
a=np.sqrt(arr)

In [86]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

 # unary operation

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [89]:
arra=np.random.randn(10)

In [90]:
arra

array([-1.00127302,  0.22584188,  1.08551385, -0.56091167, -1.87851741,
       -0.31192007, -0.2933714 ,  1.12131382, -0.67925119, -1.20307827])

In [91]:
np.abs(arra)

array([1.00127302, 0.22584188, 1.08551385, 0.56091167, 1.87851741,
       0.31192007, 0.2933714 , 1.12131382, 0.67925119, 1.20307827])

In [92]:
np.fabs(arra)

array([1.00127302, 0.22584188, 1.08551385, 0.56091167, 1.87851741,
       0.31192007, 0.2933714 , 1.12131382, 0.67925119, 1.20307827])

In [93]:
np.sqrt(arra)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.47522824, 1.04187996,        nan,        nan,
              nan,        nan, 1.05892106,        nan,        nan])

In [94]:
np.square(arra)

array([1.00254765, 0.05100456, 1.17834032, 0.3146219 , 3.52882767,
       0.09729413, 0.08606678, 1.25734468, 0.46138218, 1.44739731])

In [95]:
arra*arra

array([1.00254765, 0.05100456, 1.17834032, 0.3146219 , 3.52882767,
       0.09729413, 0.08606678, 1.25734468, 0.46138218, 1.44739731])

In [96]:
np.exp(arra)

array([0.36741142, 1.25337747, 2.96096091, 0.57068855, 0.1528165 ,
       0.73204003, 0.74574512, 3.06888351, 0.50699649, 0.30026848])

In [97]:
np.log2(arra)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([        nan, -2.14661502,  0.11837813,         nan,         nan,
               nan,         nan,  0.16519009,         nan,         nan])

In [98]:
np.log(arra)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([        nan, -1.48792015,  0.08205347,         nan,         nan,
               nan,         nan,  0.11450105,         nan,         nan])

In [99]:
np.log10(np.array([100]))

array([2.])

In [100]:
np.sign(arra)

array([-1.,  1.,  1., -1., -1., -1., -1.,  1., -1., -1.])

In [101]:
np.ceil(arra)

array([-1.,  1.,  2., -0., -1., -0., -0.,  2., -0., -1.])

In [102]:
np.floor(arra)

array([-2.,  0.,  1., -1., -2., -1., -1.,  1., -1., -2.])

In [103]:
np.rint(arra)

array([-1.,  0.,  1., -1., -2., -0., -0.,  1., -1., -1.])

In [104]:
r,q=np.modf(arra)

In [105]:
print(r)
print(q)

[-0.00127302  0.22584188  0.08551385 -0.56091167 -0.87851741 -0.31192007
 -0.2933714   0.12131382 -0.67925119 -0.20307827]
[-1.  0.  1. -0. -1. -0. -0.  1. -0. -1.]


In [106]:
s=np.sqrt(arra)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [107]:
s


array([       nan, 0.47522824, 1.04187996,        nan,        nan,
              nan,        nan, 1.05892106,        nan,        nan])

In [108]:
np.isnan(s)

array([ True, False, False,  True,  True,  True,  True, False,  True,
        True])

In [109]:
np.isfinite(s)

array([False,  True,  True, False, False, False, False,  True, False,
       False])

In [110]:
np.isinf(s)

array([False, False, False, False, False, False, False, False, False,
       False])

In [111]:
import math

In [112]:
np.cos(np.array([math.pi/3]))

array([0.5])

In [113]:
np.cos(arra)

array([ 0.53923066,  0.97460593,  0.46645824,  0.84677049, -0.30288756,
        0.95174608,  0.95727437,  0.4344995 ,  0.77804335,  0.35948698])

In [114]:
np.sin(np.array([math.pi/6]))

array([0.5])

In [115]:
np.tan(np.array([math.pi/4]))

array([1.])

In [116]:
np.sinh(np.array([math.pi/6]))

array([0.54785347])

In [117]:
np.logical_not(arra)

array([False, False, False, False, False, False, False, False, False,
       False])

# binary operation

In [118]:
x=np.random.randn(10)

In [119]:
y=np.random.randn(10)

In [120]:
print(x,"\n",y)

[ 0.00916135 -1.03392794  0.83644305  0.65126206  0.16896791 -0.27296176
  0.15974109 -0.6888442  -0.24854677 -1.74650784] 
 [ 0.13182387 -1.20607143 -0.01930461 -0.66597691  1.18051346 -0.70568498
 -0.71245886  1.35764225  0.74018722 -0.30222299]


In [121]:
np.add(x,y)

array([ 0.14098522, -2.23999937,  0.81713844, -0.01471485,  1.34948137,
       -0.97864675, -0.55271777,  0.66879804,  0.49164044, -2.04873083])

In [122]:
np.subtract(x,y)

array([-0.12266252,  0.17214349,  0.85574767,  1.31723897, -1.01154554,
        0.43272322,  0.87219995, -2.04648645, -0.98873399, -1.44428486])

In [123]:
np.multiply(x,y)

array([ 1.20768484e-03,  1.24699095e+00, -1.61472076e-02, -4.33725497e-01,
        1.99468894e-01,  1.92625017e-01, -1.13808956e-01, -9.35203989e-01,
       -1.83971146e-01,  5.27834816e-01])

In [124]:
np.divide(x,y)

array([  0.06949691,   0.85726924, -43.32866726,  -0.97790486,
         0.14313087,   0.38680399,  -0.22421097,  -0.50738271,
        -0.33578907,   5.77887163])

In [125]:
np.floor_divide(x,y)

array([  0.,   0., -44.,  -1.,   0.,   0.,  -1.,  -1.,  -1.,   5.])

In [126]:
np.power(np.array([3,5,9,7]),np.array([2,4,6,8]))

array([      9,     625,  531441, 5764801], dtype=int32)

In [127]:
np.maximum(x,s)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in maximum
  """Entry point for launching an IPython kernel.


array([       nan, 0.47522824, 1.04187996,        nan,        nan,
              nan,        nan, 1.05892106,        nan,        nan])

In [128]:
np.fmax(x,s)

array([ 0.00916135,  0.47522824,  1.04187996,  0.65126206,  0.16896791,
       -0.27296176,  0.15974109,  1.05892106, -0.24854677, -1.74650784])

In [129]:
np.mod(np.array([3,5,9,7]),np.array([2,4,6,8]))

array([1, 1, 3, 7], dtype=int32)

In [130]:
np.mod(np.array([3,5,9,7]),3)

array([0, 2, 0, 1], dtype=int32)

In [131]:
x


array([ 0.00916135, -1.03392794,  0.83644305,  0.65126206,  0.16896791,
       -0.27296176,  0.15974109, -0.6888442 , -0.24854677, -1.74650784])

In [132]:
y

array([ 0.13182387, -1.20607143, -0.01930461, -0.66597691,  1.18051346,
       -0.70568498, -0.71245886,  1.35764225,  0.74018722, -0.30222299])

In [133]:
np.copysign(x,y)

array([ 0.00916135, -1.03392794, -0.83644305, -0.65126206,  0.16896791,
       -0.27296176, -0.15974109,  0.6888442 ,  0.24854677, -1.74650784])

In [134]:
np.greater_equal(x,y)

array([False,  True,  True,  True, False,  True,  True, False, False,
       False])

In [135]:
np.less(x,y)

array([ True, False, False, False,  True, False, False,  True,  True,
        True])

In [136]:
np.not_equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [137]:
np.logical_and(np.sign(x),np.sign(y))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [138]:
points=np.arange(-1,1,0.01)

In [139]:
points

array([-1.0000000e+00, -9.9000000e-01, -9.8000000e-01, -9.7000000e-01,
       -9.6000000e-01, -9.5000000e-01, -9.4000000e-01, -9.3000000e-01,
       -9.2000000e-01, -9.1000000e-01, -9.0000000e-01, -8.9000000e-01,
       -8.8000000e-01, -8.7000000e-01, -8.6000000e-01, -8.5000000e-01,
       -8.4000000e-01, -8.3000000e-01, -8.2000000e-01, -8.1000000e-01,
       -8.0000000e-01, -7.9000000e-01, -7.8000000e-01, -7.7000000e-01,
       -7.6000000e-01, -7.5000000e-01, -7.4000000e-01, -7.3000000e-01,
       -7.2000000e-01, -7.1000000e-01, -7.0000000e-01, -6.9000000e-01,
       -6.8000000e-01, -6.7000000e-01, -6.6000000e-01, -6.5000000e-01,
       -6.4000000e-01, -6.3000000e-01, -6.2000000e-01, -6.1000000e-01,
       -6.0000000e-01, -5.9000000e-01, -5.8000000e-01, -5.7000000e-01,
       -5.6000000e-01, -5.5000000e-01, -5.4000000e-01, -5.3000000e-01,
       -5.2000000e-01, -5.1000000e-01, -5.0000000e-01, -4.9000000e-01,
       -4.8000000e-01, -4.7000000e-01, -4.6000000e-01, -4.5000000e-01,
      

In [140]:
xs,ys=np.meshgrid(points,points)
print(xs)
print(ys)

[[-1.   -0.99 -0.98 ...  0.97  0.98  0.99]
 [-1.   -0.99 -0.98 ...  0.97  0.98  0.99]
 [-1.   -0.99 -0.98 ...  0.97  0.98  0.99]
 ...
 [-1.   -0.99 -0.98 ...  0.97  0.98  0.99]
 [-1.   -0.99 -0.98 ...  0.97  0.98  0.99]
 [-1.   -0.99 -0.98 ...  0.97  0.98  0.99]]
[[-1.   -1.   -1.   ... -1.   -1.   -1.  ]
 [-0.99 -0.99 -0.99 ... -0.99 -0.99 -0.99]
 [-0.98 -0.98 -0.98 ... -0.98 -0.98 -0.98]
 ...
 [ 0.97  0.97  0.97 ...  0.97  0.97  0.97]
 [ 0.98  0.98  0.98 ...  0.98  0.98  0.98]
 [ 0.99  0.99  0.99 ...  0.99  0.99  0.99]]


In [141]:
xs.shape

(200, 200)

In [142]:
ys.shape

(200, 200)

In [143]:
z=np.sqrt(xs**2+ys**2)

In [144]:
import matplotlib.pyplot as plt
plt.imshow(z,cmap=plt.cm.ocean);plt.colorbar();plt.title("hshshsh")

Text(0.5, 1.0, 'hshshsh')

In [145]:
dir(plt.cm)

['Accent',
 'Accent_r',
 'Blues',
 'Blues_r',
 'BrBG',
 'BrBG_r',
 'BuGn',
 'BuGn_r',
 'BuPu',
 'BuPu_r',
 'CMRmap',
 'CMRmap_r',
 'Dark2',
 'Dark2_r',
 'GnBu',
 'GnBu_r',
 'Greens',
 'Greens_r',
 'Greys',
 'Greys_r',
 'LUTSIZE',
 'OrRd',
 'OrRd_r',
 'Oranges',
 'Oranges_r',
 'PRGn',
 'PRGn_r',
 'Paired',
 'Paired_r',
 'Pastel1',
 'Pastel1_r',
 'Pastel2',
 'Pastel2_r',
 'PiYG',
 'PiYG_r',
 'PuBu',
 'PuBuGn',
 'PuBuGn_r',
 'PuBu_r',
 'PuOr',
 'PuOr_r',
 'PuRd',
 'PuRd_r',
 'Purples',
 'Purples_r',
 'RdBu',
 'RdBu_r',
 'RdGy',
 'RdGy_r',
 'RdPu',
 'RdPu_r',
 'RdYlBu',
 'RdYlBu_r',
 'RdYlGn',
 'RdYlGn_r',
 'Reds',
 'Reds_r',
 'ScalarMappable',
 'Set1',
 'Set1_r',
 'Set2',
 'Set2_r',
 'Set3',
 'Set3_r',
 'Spectral',
 'Spectral_r',
 'Wistia',
 'Wistia_r',
 'YlGn',
 'YlGnBu',
 'YlGnBu_r',
 'YlGn_r',
 'YlOrBr',
 'YlOrBr_r',
 'YlOrRd',
 'YlOrRd_r',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_generate_cmap',
 '_reverse_cma

# CONDITIONAL LOGIC OPERTION

In [146]:
arr1=np.array([3,5.6,3.12,7.45,47.4])
arr2=np.array([4.2,5.6,37.8,6,34.9])
cond=np.array([True,False,True,True,False])


In [147]:
result=[(x if c else y)for x,y,c in zip(arr1,arr2,cond)]

In [148]:
result

[3.0, 5.6, 3.12, 7.45, 34.9]

In [149]:
np.where(cond,arr1,arr2)

array([ 3.  ,  5.6 ,  3.12,  7.45, 34.9 ])

In [150]:
arr=np.random.randn(4,4)

In [151]:
arr

array([[-0.31611217, -0.43593443,  0.09326822,  0.43477281],
       [-0.4994511 , -0.39985235,  0.68516886, -0.63990299],
       [-0.89601919,  0.05870101,  0.98708241,  1.38089354],
       [-0.68501709,  1.45451531,  0.05589792, -1.50870127]])

In [152]:
c=arr>0

In [153]:
np.where(c,arr,0)

array([[0.        , 0.        , 0.09326822, 0.43477281],
       [0.        , 0.        , 0.68516886, 0.        ],
       [0.        , 0.05870101, 0.98708241, 1.38089354],
       [0.        , 1.45451531, 0.05589792, 0.        ]])

# STATICIAL  AND MATHEMATICAL OPERTIONS


In [154]:
 u=np.arange(20).reshape((5,4))

In [155]:
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [156]:
np.mean(u)

9.5

In [157]:
u.mean()

9.5

In [158]:
u.sum()

190

In [159]:
np.sum(u)

190

In [160]:
np.sum(u,axis=1)

array([ 6, 22, 38, 54, 70])

In [161]:
u.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [162]:
u.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

In [163]:
u.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70]], dtype=int32)

In [164]:
u.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)

In [165]:
arr=np.arange(8)
arr.mean()

3.5

In [166]:
arr.mean(axis=0)

3.5

In [167]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [168]:
arr.sum(axis=0)

28

In [169]:
u.sum()

190

In [170]:
u.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [171]:
u.sum(axis=0)

array([40, 45, 50, 55])

In [172]:
u.mean()

9.5

In [173]:
u.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [174]:
u.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [175]:
u.std()

5.766281297335398

In [176]:
u.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [177]:
u.std(axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])

In [178]:
u.var()

33.25

In [179]:
u.min()

0

In [180]:
u.min(axis=1)

array([ 0,  4,  8, 12, 16])

In [181]:
u.min(axis=0)

array([0, 1, 2, 3])

In [182]:
u.max(axis=0)

array([16, 17, 18, 19])

In [183]:
u.max(axis=1)

array([ 3,  7, 11, 15, 19])

In [184]:
u.argmin()

0

In [185]:
u[3][2],u[2][3]=0,67


In [186]:
u

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 67],
       [12, 13,  0, 15],
       [16, 17, 18, 19]])

In [187]:
u.argmin(axis=0)##giving indices

array([0, 0, 3, 0], dtype=int64)

In [188]:
u.argmin(axis=1)##giving indices

array([0, 0, 0, 2, 0], dtype=int64)

In [189]:
u.argmax()

11

In [190]:
u.argmax(axis=1)

array([3, 3, 3, 3, 3], dtype=int64)

In [191]:
u.argmax(axis=0)

array([4, 4, 4, 2], dtype=int64)

In [192]:
u.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55, 122, 134,
       147, 147, 162, 178, 195, 213, 232], dtype=int32)

In [193]:
u.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

In [194]:
u.cumprod(axis=1)

array([[    0,     0,     0,     0],
       [    4,    20,   120,   840],
       [    8,    72,   720, 48240],
       [   12,   156,     0,     0],
       [   16,   272,  4896, 93024]], dtype=int32)

In [195]:
np.cumprod(u,axis=0)

array([[     0,      1,      2,      3],
       [     0,      5,     12,     21],
       [     0,     45,    120,   1407],
       [     0,    585,      0,  21105],
       [     0,   9945,      0, 400995]], dtype=int32)

# METHOD FOR BOOLEAN ARRAY 

In [196]:
arr=np.random.randn(100)

In [197]:
a=arr>0

In [198]:
a.sum()

48

In [199]:
a

array([False, False, False, False,  True,  True, False, False,  True,
        True, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
       False, False, False,  True, False,  True, False, False, False,
       False,  True,  True,  True,  True, False, False, False,  True,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False,  True,  True, False, False,  True, False,
        True,  True, False, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True, False, False, False, False,  True, False, False,  True,
       False])

In [200]:
b=np.array([True,False,True,False,True,True,True])
b.any()

True

In [201]:
b.all()

False

In [202]:
ar=np.random.randn(5,5)

In [203]:
ar


array([[-0.24419341,  0.70798977, -1.13862223, -0.70887938,  0.36529122],
       [ 0.6820435 ,  0.01456237, -0.29279177, -0.3816671 ,  0.84582753],
       [-1.53884136, -1.72820684,  1.1058564 , -0.69693475, -0.98052566],
       [ 0.54201448,  0.90150855, -1.50193206, -1.72866993, -0.33097177],
       [-1.6392833 , -1.60984825,  0.48854114, -1.02686863,  0.86442723]])

In [204]:
ar.sort(1)

In [205]:
ar

array([[-1.13862223, -0.70887938, -0.24419341,  0.36529122,  0.70798977],
       [-0.3816671 , -0.29279177,  0.01456237,  0.6820435 ,  0.84582753],
       [-1.72820684, -1.53884136, -0.98052566, -0.69693475,  1.1058564 ],
       [-1.72866993, -1.50193206, -0.33097177,  0.54201448,  0.90150855],
       [-1.6392833 , -1.60984825, -1.02686863,  0.48854114,  0.86442723]])

In [206]:
ar.sort(0)

In [207]:
ar

array([[-1.72866993, -1.60984825, -1.02686863, -0.69693475,  0.70798977],
       [-1.72820684, -1.53884136, -0.98052566,  0.36529122,  0.84582753],
       [-1.6392833 , -1.50193206, -0.33097177,  0.48854114,  0.86442723],
       [-1.13862223, -0.70887938, -0.24419341,  0.54201448,  0.90150855],
       [-0.3816671 , -0.29279177,  0.01456237,  0.6820435 ,  1.1058564 ]])

# UNIQUE AND SET LOGIC

In [208]:
arr=np.array([1,4,5,1,6,8,1,7,1,7,8,4,3,7])

In [209]:
np.unique(arr)

array([1, 3, 4, 5, 6, 7, 8])

In [210]:
np.in1d(arr,[2,3,4])

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True,  True, False])

In [211]:
arr1=np.array([1,2,6,3,8,3,7,2,8,7])


In [212]:
np.unique(arr1)

array([1, 2, 3, 6, 7, 8])

In [213]:
np.intersect1d(arr,arr1)

array([1, 3, 6, 7, 8])

In [214]:
np.union1d(arr,arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [215]:
np.setdiff1d(arr,arr1)

array([4, 5])

In [216]:
np.setxor1d(arr,arr1)

array([2, 4, 5])

# FILE INPUT ND OUTPUT WITH ARRAY

In [217]:
  arr=np.arange(10)

In [218]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [219]:
np.save("some_array",arr)

In [220]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [221]:
arr1=np.array([3,4,5,3,9,1,5,10])

In [222]:
np.savez("array_achive.npz",a=arr,b=arr1,c=np.array([6,36,38,89]))

In [223]:
a=np.load("array_achive.npz")

In [224]:
a["a"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
a["b"]

array([ 3,  4,  5,  3,  9,  1,  5, 10])

In [226]:
a["c"]

array([ 6, 36, 38, 89])

# LINEAR ALGEBRA 

In [227]:
a=np.array([[1,2,4,5,6],[1,4,5,6,7]])
b=np.array([[1,3],[34,67],[2,8],[4,7],[2,7]])

In [228]:
a

array([[1, 2, 4, 5, 6],
       [1, 4, 5, 6, 7]])

In [229]:
b

array([[ 1,  3],
       [34, 67],
       [ 2,  8],
       [ 4,  7],
       [ 2,  7]])

In [230]:
a.dot(b)

array([[109, 246],
       [185, 402]])

In [231]:
np.dot(a,b)

array([[109, 246],
       [185, 402]])

In [232]:
b.dot(a)

array([[  4,  14,  19,  23,  27],
       [101, 336, 471, 572, 673],
       [ 10,  36,  48,  58,  68],
       [ 11,  36,  51,  62,  73],
       [  9,  32,  43,  52,  61]])

In [233]:
np.ones(3)

array([1., 1., 1.])

In [234]:
a@b

array([[109, 246],
       [185, 402]])

In [235]:
 ab=np.arange(16).reshape((4,4))

In [236]:
ab

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [237]:
from numpy.linalg import *

In [238]:
np.diag(ab)

array([ 0,  5, 10, 15])

In [239]:
np.diag([2,4,6,7])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 7]])

In [240]:
np.trace(ab)

30

In [241]:
det(ab)

-2.9582283945787796e-30

In [242]:
eig(ab)

(array([ 3.24642492e+01, -2.46424920e+00,  1.92979794e-15, -4.09576009e-16]),
 array([[-0.11417645, -0.7327781 ,  0.54500164,  0.00135151],
        [-0.3300046 , -0.28974835, -0.68602671,  0.40644504],
        [-0.54583275,  0.15328139, -0.2629515 , -0.8169446 ],
        [-0.76166089,  0.59631113,  0.40397657,  0.40914805]]))

In [243]:
inv(ab)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [244]:
qr(ab)

(array([[ 0.        , -0.83666003,  0.48308786,  0.25812035],
        [-0.26726124, -0.47809144, -0.8365087 ,  0.01591196],
        [-0.53452248, -0.11952286,  0.22375381, -0.80618499],
        [-0.80178373,  0.23904572,  0.12966702,  0.53215267]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.71941189e-15,
         -5.12511879e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -8.82043219e-16]]))

In [245]:
svd(ab)

(array([[-0.09184212, -0.83160389,  0.52939495,  0.14050262],
        [-0.31812733, -0.44586433, -0.8105844 ,  0.20725087],
        [-0.54441254, -0.06012478,  0.03298396, -0.8360096 ],
        [-0.77069775,  0.32561478,  0.2482055 ,  0.48825611]]),
 array([3.51399637e+01, 2.27661021e+00, 8.80118491e-16, 4.41188001e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [ 0.5427818 , -0.66899815, -0.29034911,  0.41656546],
        [ 0.0734024 , -0.50243554,  0.78466387, -0.35563073]]))

In [246]:
solve(ab,[3,4,5,4])

array([-2.70215978e+15,  4.20335965e+15, -3.00239975e+14, -1.20095990e+15])